/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.13/samples
 */
plugins {
    kotlin("jvm") version "1.9.22"
    id("com.github.johnrengelman.shadow") version "8.1.1"
    // We're not using the plugin-yml-bukkit plugin anymore since we're providing our own plugin.yml
}

group = "zepsizola.me"
version = "1.0"

repositories {
    mavenCentral()
    maven("https://repo.papermc.io/repository/maven-public/")
}

dependencies {
    // Using Paper API instead of Folia API for better compatibility
    compileOnly("io.papermc.paper:paper-api:1.20.4-R0.1-SNAPSHOT")
    implementation(kotlin("stdlib"))
}

tasks {
    compileKotlin {
        kotlinOptions.jvmTarget = "17"
    }
    
    compileJava {
        options.release.set(17)
    }
    
    shadowJar {
        archiveClassifier.set("")
        relocate("kotlin", "me.zepsizola.zcommandcooldown.lib.kotlin")
    }
    
    build {
        dependsOn(shadowJar)
    }
}
